### ISSUE TITLE
New - Blockchain enhancement of FITBIR informatics system

### ISSUE THREAD

**Issue by stmanion** [GSA/emerging-technology-atlas#1]
The Federal Interagency Traumatic Brain Injury Research (FITBIR) informatics system (https://fitbir.nih.gov/) was developed to share data across the entire TBI research field and to facilitate collaboration between laboratories, as well as interconnectivity with other informatics platforms.

Blockchain and related smart contract technologies could be used to automate processing and increased controlled access for researchers. This would reduce cost of operation, increase the return on investment of government research dollars, and advance evidence-based care for those suffering the effects of TBI.

This use case was presented at the Military Health System Research Symposium 2017 as part of, "Blockchain Technology Framework for Operational Precision Medicine," by Sean Manion, Lauren Long, John Reusing, and Bruce Doll

Agencies: DoD (USUHS, MRMC, DHA), VA, HHS (NIH); Status: Concept phase, unfunded

**Comment by ryanwoldatwork** [comment]
Hi @stmanion,

Are there any updates on the FITBIT blockchain effort?

And, is there something the Emerging Tech Atlas website can assist as it relates to this issue?
