### ISSUE TITLE
NYC Immutable Cross-Agency ledger

### ISSUE THREAD

**Issue by LawsonDoITT** [GSA/emerging-technology-atlas#18]
CityWide Asset Ledger - Hybrid (Private/Public) Blockchain to track all Assets for The City of New York - 512-bit Encrypted
A Blockchain with built-in Smart Contracts to track all Citywide Assets for The City of New York. Tamper Proof, Immutable, 100% availability.
Roadmap:
Stage 1 - Property and Car Titles, Death and Marriage Certificates, Agency to Agency agreements, IoT Assets, contracts and transactions, Transport tracking and Transactions within.
Stage 2 - All types of City Benefits and Any form of Public record or agreements between city agencies
Absolute fraud protection on all transactions, no middlemen, fast Transaction times and absolutely un-hackable due to 512bit encryption and the consensus algorithm across ledgers.
Stage 3 – Neural Network and cortical learning analyzing dataset's from all city agencies and creating contracts and agreements automatically + reinforcement learning.
Stage 4 add contracts associated with compliance and audit.
https://github.com/LawsonDoITT/CAL-CitywideAssetLedger

**Comment by AskMPMUnbound2016** [comment]
Our organization would love to learn more about your initiative. We are finalizing a smart contract as a service component to our real-time asset tracking & monitoring platform. We're working with BiTA(Blockchain in Transportation Alliance) to QA it. Our predefined contract will focus on managing physical, human, or digital assets for transparency and traceability by tying the movement of those assets to geo-location. 

The key is separating the application from the contract components and marrying the system integrations required to make it all come together cohesively. Then you can build events and triggers for integrity and oversight. The architecture must be scalable and flexible to adapt not only to the changes that will inevitably take place in your business process but to ensure the computing resources needed are minimized. Platforms that are reliant on mining to manage may not be best suited for your use case. Only the discovery will unfold that story but it is worth noting. Please email me at marvin@ovalz.io we'd love to chat with you about your project.

Best,
Marvin

**Comment by ryanwoldatwork** [comment]
Hi @LawsonDoITT,

What have you learned from the CityWide Asset Ledger effort?

It looks like the repo hasn't been updated in 2 years, and I'm curious what went well and what challenges were.
