### ISSUE TITLE
Potential New Blockchain Resource/Call to Action: NIST Blockchain Overview Draft Released

### ISSUE THREAD

**Issue by sunny32920** [GSA/emerging-technology-atlas#20]
I hope I'm not totally stealing their thunder, but I'm so excited about this!  Yesterday NIST released their draft 60-page blockchain overview!!!
https://csrc.nist.gov/publications/detail/nistir/8202/draft

Comments are due: February 23, 2018

--Sherri Sokol
(DISA)

**Comment by JustinHerman** [comment]
-- Sherri this is fantastic -- we're adding!
