### ISSUE TITLE
Looking to team on a VR/AR project 

### ISSUE THREAD

**Issue by KenNvent4u** [GSA/emerging-technology-atlas#22]
I am looking for partners on a Smart Cities / AR/VR pilot project. The project is a part of the Challenge.gov NIST VR heads-up display challenge. Our concept just moved on to Phase Two which is the team building phase. The project involves two NIST Challenges the VR heads-up display challenge and the Global Cities Teams Challenge (GCTC). 
The VR/AR concept deals with developing an interface for first responders. The project is also related this year’s GCTC Smart and Secure cities Challenge. I think this is a good opportunity for the Community of Practice to team on a live pilot. Our concept involves both GIS (AGOL 3D Model and .IFC data) and 100 Gigabit fiber network solutions.  I am hoping to use the GCTC and the Emerging Technology Community of Practice as an opportunity to build a team with a large knowledge base. Let me know if this is something the group can work on together. 
Thanks
Ken

**Comment by ty-garman** [comment]
You might check out VibeHub.  While they are focused on a very different sector of AR/VR, there might be opportunities within their platform or community worth pursuing.  Best of luck!

**Comment by hectorferronato** [comment]
Hi @KenNvent4u ! I'm part of a tech solutions company and we are tackling multiple challenges in the VR/AR space. What's the best way for us to get in touch?

**Comment by KenNvent4u** [comment]
ken@ncpc.gov

**Comment by KenNvent4u** [comment]
202 482-7261

**Comment by ryanwoldatwork** [comment]
Any updates here?
