### ISSUE TITLE
Looking for partners to evaluate blockchain tech for the Energy Service Industry

### ISSUE THREAD

**Issue by tapan89** [GSA/emerging-technology-atlas#23]
Hi All,

Really glad to be part of ECTO group! As the title says, I'm looking for people with interest in evaluating blockchain for the Energy Services Industry. I am a USACE researcher working with DoD sites on renewable energy, microgrids, energy savings, etc. There are several companies and concepts that can alter the way DoD (and Federal Agencies) spends on energy consumption. I'd like to have some discussions and work with others to apply for and secure funding for pilot initiatives in this area. Please let me know if you're interested or if you have any suggestions on how to approach this topic.

-- Tapan Patel (USACE ERDC-CERL)

**Comment by 3dangreen** [comment]
Tapan
 The Department of the Navy is  beginning some experimentation on Transactional Energy, microgrids and blockchain.  It would be good to have Army participate and for us to loop you into our discussions with DOE and our regional microgrid partners.   Contract me at dan.green@navy.mil and we begin the dialog.  -- Dan Green (SECNAV Naval Innovation Advisory Council)

**Comment by AskMPMUnbound2016** [comment]
We are interested in talking with organizations to tie the use of FHE sensors to our blockchain for real-time human, environmental, and physical asset protection. Our organization would be interested in talking about ways we could partner. Please contact me at marvin@ovalz.io. 

Marvin Harris (Ovalz)
