### ISSUE TITLE
Blockchain Resources 

### ISSUE THREAD

**Issue by jasonmiller43** [GSA/emerging-technology-atlas#3]

**Comment by JustinHerman** [comment]
Hi Jason -- you came so close -- there's no text in your comment on Blockchain Resouces -- have you any to contribute?

**Comment by jasonmiller43** [comment]
Sorry about that, yes I do. I got distracted and then incredibly busy, but
I'll add some content when I get a chance.

**Comment by BlockchainMoses** [comment]
https://entethalliance.org

COMMUNITY & RESOURCES In partnership with the dedicated and robust Ethereum community, Enterprises are coming together to produce the industry standard, open source, free to use blockchain solutions that will be the foundation for businesses going forward.

**Comment by jasonmiller2134** [comment]
Coin Center's State-by-State Regulatory Tracker for Digital Currency Policy: https://coincenter.org/page/state-digital-currency-regulatory-tracker 

Provides up to date info on blockchain related bills and their progress for each state.
