### ISSUE TITLE
HUD customer service chat bot

### ISSUE THREAD

**Issue by markbubel** [GSA/emerging-technology-atlas#4]
The @HUD-Digital-Services Team over at HUD has built a prototype chat bot using Microsoft's [Bot Framework](https://dev.botframework.com) and [QnA Maker](https://qnamaker.ai). We're continuing to make improvements to it and test it with staff inside HUD and eventually citizens as well. This is still very much a prototype to demonstrate some possibilities. 

The Bot Framework provides the foundation of making the bot work and accessible on the web.
The QnA Maker provides NLP capability without having to build intents, utterances, etc.

Our chat bot is HUD's first exploration of AI. The purpose of HUD's chat bot is to provide a front-line of help for citizens looking for information about rental assistance, information about HUD programs, and procedures for sending discrimination complaints.

We want the chat bot to assist HUD in delivering accurate, easy-to-find information at the medium of the citizen's choice: web, Facebook, SMS, etc. Further down the road, we want to integrate the chat bot with our CRM solution to facilitate case intake and servicing by HUD customer service staff.

[Repo for the chat bot](https://github.com/HUD-Digital-Services/customer-service-bot)

[Publicly-Accessible link](https://hud-rental-assistance-bot.herokuapp.com) to test the bot

**Comment by SandyB1** [comment]
Have you played with mixing the bot, Ai, with AR to create a KIOSK?
