### ISSUE TITLE
GBA Has Free Resources for Civil Servants

### ISSUE THREAD

**Issue by grdache** [GSA/emerging-technology-atlas#6]
Could you please add the note text on the Resources page that:

1)  Membership in the GSA is free to civil servants and provide a link to https://governmentblockchain.org/membership

2) GBA has locations around the country where civil servants can receive free training and provide a link to:
https://governmentblockchain.org/blockchain-resources/working-groups-location-chapters

3)  Civil servants are encouraged to join blockchain related working groups for free at:
https://governmentblockchain.org/working-groups

**Comment by grdache** [comment]
Could you please add the Government Blockchain Association (GSA) to the list of participants on the following page:  
https://gsa.github.io/emerging-technology-atlas/blockchain-workshop

**Comment by thagerdc** [comment]
Could you throw in Macro Solutions too?  Thanks!
