### ISSUE TITLE
ConsenSys Academy 

### ISSUE THREAD

**Issue by BlockchainMoses** [GSA/emerging-technology-atlas#7]
Ask me about our soon to be released course for attorneys on blockchain, that will offer CLE credits.  Good for policymakers!  Email me at jason.brett@consensys.net if you are a civil servant and an attorney interested in blockchain.

**Comment by JustinHerman** [comment]
Regretfully this falls under "Promotion or endorsement of commercial services, products, or entities", so we will not be able to add, but please keep the contributions coming. Thanks.

**Comment by BlockchainMoses** [comment]
Ah, understood!


*Jason Brett* // @dowithcare
jason.brett@consensys.net / +1 202 553 6972
1440 G St. NW Washington DC 20005
Web <https://consensys.net/> | Twitter <https://twitter.com/ConsenSysLLC> |
Facebook <https://www.facebook.com/consensussystems> | Linkedin
<https://www.linkedin.com/company/consensus-systems-consensys-> | Newsletter
<http://consensys.us11.list-manage.com/subscribe?u=947c9b18fc27e0b00fc2ad055&id=257df01285&utm_content=buffer1ce12&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer>

**Comment by thagerdc** [comment]
I love the moniker, Jason..  Fitting!!
